# Generated by Django 4.0.4 on 2022-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0002_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='glossary',
        ),
        migrations.AddField(
            model_name='novel',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='translators.genre'),
        ),
        migrations.DeleteModel(
            name='Glossary',
        ),
    ]
