# Generated by Django 4.0.4 on 2022-07-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0003_remove_novel_glossary_novel_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='synopsis',
            field=models.TextField(default='Filler'),
            preserve_default=False,
        ),
    ]
