# Generated by Django 4.0.4 on 2022-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0004_novel_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='raws',
            field=models.FileField(default='test', upload_to='parsing_stuff'),
            preserve_default=False,
        ),
    ]
