# Generated by Django 4.0.4 on 2022-07-18 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0005_novel_raws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='raws',
            field=models.FileField(upload_to='translators/parsing_stuff/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Title must be longer than 5 characters')]),
        ),
    ]
