# Generated by Django 4.0.4 on 2022-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0007_alter_chapter_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
