# Generated by Django 4.0.4 on 2022-07-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0008_alter_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
